### ISSUE TITLE
problem with new release 1.2.5

### ISSUE THREAD

**Issue by andrikz** [TECLIB/formcreator#119]
i updated formcreator from 1.2.4 version to 1.2.5 and now, all my forms now show this error:

![screenshot_8](https://cloud.githubusercontent.com/assets/7794575/9246922/d9f5938a-41b7-11e5-8404-2355bd4f2e18.png)

and another question is about ticket registration by entities, is it possible to include this feature in next versions?

**Comment by neeftarah** [comment]
Hi,

The message "Cannot generate target" effectively appear every-time.
It will be fixed in next release. To correct this manually now, see commit bellow.


For entities, you already can create your forms by entity. Like all object in GLPI, when you create a form, it is automatically created and associated to the entity where you are.
It will be only available in that entity and sub-entities if you enter "Yes" to the "sub-entities" field.

Moreover, when a user answers to a form, the tickets are generated in the user's entity.

If that feature doesn't meet to your needs, please give me more details on your wishes, needs and uses.

Best regards,
Jérémy

**Comment by andrikz** [comment]
thx for answer about "cannot generate targets!"

i understand, that form generates ticket in that entity where is user.

my situation looks like this:
self-service users are in the entity: "Main entity", but technicians are in the "Main entity > departmen A", "Main entity > depratment B" and so on...

when self-service users try to submit ticket with form, it will be registered in "Main entity", but technicians in the sub-entity can't see it.

and this thing i can't manage by 'business rules' in GLPI. There is only alike rule in "Rules for assigning a ticket created through a mails receiver" when we can define entity for ticket.

Maybe you need more details about my situation by e-mail or another opened issue?

Best regards,
Andrew

**Comment by neeftarah** [comment]
You can use ticket template to add predefined fields and tickets rules to attribute an entity from the value of a field or from source (witch is set to Formcreator for ticket created from it).

But for now, you wont be able to define rules from an answer to a question.
